ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_user: controler
ansible_password: C0nTroll3r124#@
ansible_become: true
ansible_become_method: enable
ansible_become_password: C0nTroll3r124#@
